### ISSUE TITLE
[feat] binary data

### ISSUE THREAD

**Issue by matteoturini** [seald/nedb#24]
**Is your feature request related to a problem? Please describe.**
I want to store binary files as a database field without resorting to creating and managing real files on a filesystem.

**Describe the solution you'd like**
Moving to a binary-encoded json-like format or adding a way to reference a separate database with the actual binary data.

**Describe alternatives you've considered**
Creating a package to serve as a store for binary files

**Comment by tex0l** [comment]
I'm sorry, this is not something we are prepared to do, I suggest you encode them in base64 even though it takes up more space.
