### ISSUE TITLE
did you look at this commit for bigger databases?

### ISSUE THREAD

**Issue by akaJes** [seald/nedb#3]
it could be good for big databases
https://github.com/louischatriot/nedb/pull/463

**Comment by tex0l** [comment]
Hi @akaJes,
I didn't know this, this seems like a good idea!

I won't have to time to port the changes to @sealdio/nedb. However I'll be able to review & merge an MR that implements the changes & tests, feel free to open it :).

**Comment by arantes555** [comment]
Implemented in https://github.com/seald/nedb/pull/5
