### ISSUE TITLE
[Question] There is the  ability to open databases in read-only mode ?

### ISSUE THREAD

**Issue by p4535992** [seald/nedb#31]
**Is your feature request related to a problem? Please describe.**

No bugs involved, I just have a question and I'm having trouble finding the answer to about a possibile limitation of nedb.

Whatever replacement you create/find, it is possible to open db files in read-only ? or in other words there is the  ability to open databases in read-only mode ?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tex0l** [comment]
No, NeDB doesn't provide a read-only mode.

Can't you copy/paste the Datastore file then open this one instead?

**Comment by p4535992** [comment]
My use case was to perform operations with the confidence that I would not modify the db file database, the copy paste solution however effective does not solve my use case, thank you very much for your response and your work on this project.
