### ISSUE TITLE
Add notice about nedb-promises

### ISSUE THREAD

**Issue by RollingHog** [seald/nedb#4]
This, to be exact https://www.npmjs.com/package/nedb-promises

**Comment by tex0l** [comment]
done in #11

**Comment by RollingHog** [comment]
where exactly its done there?

**Comment by tex0l** [comment]
In this commit: https://github.com/seald/nedb/pull/11/commits/df358b91a64509f4ac5f331b80a51db3d3e57a85#

**Comment by RollingHog** [comment]
Aha, I see, many thanks. Will close issue as soon as it will be merged.

**Comment by arantes555** [comment]
BTW, the PR in question will kinda make nedb-promises redundant.

**Comment by tex0l** [comment]
Indeed, as you can see in the branch https://github.com/seald/nedb/tree/remove-async and in the beta version of @seald-io/nedb (v3), we removed the `async` dependency which is very outdated replaced it by using Promises, once we were there, we decided to expose a Promise-based interface. The callback-based interface of this new version is actually the Promise-based interface callbackified.

I would recommend you test the v3 before we release it to make sure nedb-promises works properly with it. @RollingHog

**Comment by RollingHog** [comment]
If you make your own Promise interface I'm not even sure nedb-promises is needed anymore.

**Comment by tex0l** [comment]
I agree with you that nedb-promises will probably not be needed anymore with that new interface of @seald-io/nedb@3.x.x.

However some of the users of nedb-promises may not want to change their code, but may want to upgrade to the latest version of @seald-io/nedb.
This new version we are releasing does expose a Promise-based interface, but it is not a drop-in replacement for nedb-promises. I didn't want to have hybrid function that test the type of the last argument to determine whether to work with a callback or return a Promise...

Therefore the Promise interface of @seald-io/nedb v3 is another set of functions: for every function that works with a callback, there is an equivalent function suffixed with `Async`.

**Comment by tex0l** [comment]
released in v3.0.0
