### ISSUE TITLE
Why not just support `db.collection(name)` as MongoDB does

### ISSUE THREAD

**Issue by yanna92yar** [seald/nedb#41]
Hi,
I would like to port my MongoDB based project to Nedb completely. 
Having such calls:

```js
  const colListings = db.collection(Collections.Listing)
  const colUsers = db.collection(Collections.Users)

```

 Mongo needs a present collection with that name, but for Nedb, why not either get reference to that collection if persistence is chosen, or just create a new collection with that name.

I don't get it why there is a DataStore per collection.. I'm sure this has a reason from the start..

**Comment by tex0l** [comment]
Unfortunately, that is how it was built from the start. It would be very easy to simply have a wrapper create new datastores on the fly for each new collection, that's what we do in our [custom-made ODM for NeDB](https://github.com/seald/follicle) (even though it is open-sourced, only Seald uses it as far as we know, therefore it fits our use case, but may not fit yours).

I'm closing as this is a won't fix.
