### ISSUE TITLE
findAsync Cursor return should include _id

### ISSUE THREAD

**Issue by RobMayer** [seald/nedb#45]
**Describe the bug**

db.findAsyc and db.findOneAsync Cursor return type does not include _id

**Expected behavior**
If you're fetching a record or a list of records, that list of records should probably include the _id in its types
return types of insert or update include them.

**Comment by tex0l** [comment]
I changed the type of Cursor so that it extends `Promise<Document<T>>` like its method `execAsync` instead of `Promise<T>`, as Cursor is a sort of "thenable" as it reimplements manually `then`, `catch` and `finally` simply by making a call to `execAsync` followed by `then`, `catch` or `finally`.
