### ISSUE TITLE
Database file location

### ISSUE THREAD

**Issue by hakarabakara** [seald/nedb#60]
Maybe I did not understand the package properly, I understood that a physical file with the database would be available at the path provided at the initialisation of the database. 

I have loaded data but searching through the project, I cannot find the physical file. I would like to move it to a different project without having to import original data again.

Please give me guidance.

Here's how my set-up looks like:

````const db = new Datastore({ filename: "database.db", autoload: true });````

The file is not available in the project

**Comment by arantes555** [comment]
@hakarabakara is your project running on Node ? If so, there is an actual file created on disk. If you specify a full path, it will be there. If you only specify a filename, it will be in the working directory when the Datastore is created.

**Comment by hakarabakara** [comment]
My project is a React project unfortunately

**Comment by arantes555** [comment]
If you mean React in the browser, then NeDB uses https://github.com/localForage/localForage, which probably means localStorage in modern browsers. You can try exporting the localstorage from one place and re-exporting it in the other.

If you mean React-Native, then it uses https://github.com/react-native-async-storage/async-storage. You can try taking a look at their doc to figure out how to export the data, and re-import it on the other side.

Sorry, this is beyond the scope of NeDB. Closing.

**Comment by hakarabakara** [comment]
I mean React in the browser, I tried checking localStorage but there was nothing. I will continue reading the documentation for localForage and see if there's anything I can come up with. 

Thank you for taking your time to respond to my question
